version: '3'
services:
  app: 
    build: .
    command: rails s -b 0.0.0.0 
    volumes:
      - .:/usr/src
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      REDIS_URL: redis://redis:6379/0
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
    - 15672:15672
    volumes:
    - rabbit:/var/lib/rabbitmq
  db:
    image: postgres:11.5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password 
    volumes:
      - postgres:/var/lib/postgresql/data
  sidekiq:
    build: .
    # image: app
    command: sidekiq
    volumes:
      - ./:/usr/src/
    environment:
      REDIS_URL: redis://redis:6379/0
  redis:
    image: redis:alpine
    volumes:
      - redis:/data
  
volumes:
  postgres:
  rabbit:
  redis:
