version: '3'
services:
  app: 
    image: ruby:2.7-alpine
    build: .
    volumes:
      - .:/usr/src
    working_dir: /usr/src
    ports:
      - "3000:3000"
    command: rails s -b 0.0.0.0. && rails c

  db:
    image: sqlite:latest
    volumes:
      - ./db:/db
